### ISSUE TITLE
cacaphony exists with code 101 on Windows

### ISSUE THREAD

**Issue by leolivier** [subalterngames/cacophony#20]
Hi
I'm working on Windows 11 where I installed rustc 1.74:
```
PS D:\devts\cacophony> rustc -V
rustc 1.74.0 (79e9716c9 2023-11-13)
```
I cloned the repo, then ran as explained `cargo build --release` which ran ok.
```
...
   Compiling io v0.2.0 (D:\devts\cacophony\io)
   Compiling cacophony v0.2.0 (D:\devts\cacophony)
    Finished release [optimized] target(s) in 4m 28s
```
Then, I tried `cargo test --all` with good results: all tests ran did pass (although a fair number of tests were not ran)
Then I copied ./data to ./target/release `PS D:\devts\cacophony> mv .\data\ .\target\release\`
And finally tried to run cacophony with the following result:
```
PS D:\devts\cacophony> cargo run --release
    Finished release [optimized] target(s) in 0.42s
     Running `target\release\cacophony.exe`
error: process didn't exit successfully: `target\release\cacophony.exe` (exit code: 101)
```
No idea of what is happening. I tried to find the 101 error code in the source but didn't find it... (I found that "Currently, Rust sets an exit code of 101 when the process panicked.")
 Any idea of what is going wrong?

**Comment by subalterngames** [comment]
Copy + paste `data/` into its original location.

If you `cargo run --release`, cargo will launch the application located in `./target/release/` but the working directory will still be `.`, so it will find `./data/`.

If you want to run Cacophony like a normal Windows application, copy+paste `data/` into `target/release` and then double-click `Cacophony.exe`.

Let me know if that fixes the problem.

**Comment by leolivier** [comment]
Great @subalterngames , it works!
Maybe it's worth explaining in the doc?
