### ISSUE TITLE
Feature: command line options

### ISSUE THREAD

**Issue by tversteeg** [subalterngames/cacophony#4]
I'm willing to create a PR that allows some basic options to be configured with command line flags, such as the data dir. This would mean adding another crate as a dependency for the parsing. Is that in line with the goals of this project?

**Comment by subalterngames** [comment]
Thanks for the PR! Having merged it, can I close this Issue, or were you thinking of adding more env variables?

**Comment by tversteeg** [comment]
Ah no sorry about being unclear, this is not about env variables but about adding command line options, something like `cacophony --data-dir ..`

**Comment by subalterngames** [comment]
I don't think there is a need for `--data-dir`, specifically, anymore.

Most, if not all, other options should be handled in config.ini. Is there something that config.ini doesn't expose that should be modifiable?

**Comment by tversteeg** [comment]
Some things that pop up in my mind:

- Show a brief description with `--help`
- Print the current version with `--version`
- Opening an existing project by passing the project file/directory
- Possibly some window configuration like opening full screen that's not "persistent" configuration

**Comment by subalterngames** [comment]
Oh yeah, those are all good. Yes to all of them, please.
