### ISSUE TITLE
Provide a way to override default data directory

### ISSUE THREAD

**Issue by tranzystorekk** [subalterngames/cacophony#51]
For distro installations it would probably be convenient to allow maintainers to install the data files in a system location like `/usr/share/cacophony/` and then point cacophony at build time to look for those files there instead of the current whatever `./data` points to at build time.

I imagine sth like reading a `CACOPHONY_BUILD_DATA_DIR` variable and setting that as the default if it exists.

**Comment by subalterngames** [comment]
@tranzystorekk See PR. Is it doing what you asked for?

**Comment by tranzystorekk** [comment]
Yeah, exactly what I meant, thank you!
