### ISSUE TITLE
Linux build options for distros other than ubuntu

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [subalterngames/cacophony#6]
I see that the build options for linux are specifically for ubuntu, any chance those will work with other distros? I'm an Arch user and since Arch is a rolling release distro I feel like there could be some problems with dependencies.

I also use nobara, which is a fork of Fedora, (on my steam deck) that gets new system updates about every 6 months and has newer packages than what the latest ubuntu lts release has.

If that isn't the case for rust, then what would I run to build thr software?

**Comment by subalterngames** [comment]
@LovecraftianGodsKiller See this PR: https://github.com/subalterngames/cacophony/pull/7

The flags currently have misleading names. All they do is set the expected version of Speech Dispatcher. Please let me know if you can compile on Arch and nobara using the renamed flags.
